package com.web.domain;

import java.util.Date;

import lombok.Data;

@Data
public class SO {

	private String soNumber;
	private String docType;
	private Date soDate;
	private String calendarPeriod;
	private String glPeriod;
	private String postStatus;
	private String glStatus;
	private String BillStatus;
	private String deliverStatus;
	private String ReferenceOur;
	private String ReferenceYour;
	private String Terms;
	private String ContactType;
	private String CustCode;
	private String CustBranchCode;
	private String CustContactCode;
	private String CustAttention;
	private String CustName;
	private String CustAddBlock;
	private String CustAddFloor;
	private String CustAddUnit;
	private String CustAddBuilding;
	private String CustAddStreet;
	private String CustAddPostal;
	private String CustAddCountry;
	private String CustTelephone;
	private String DeliveryAddress1;

	private String DeliveryAddress2;
	private String RequireDate;
	private String DueDate;
	private String Currency;
	private String ValueOriginal;
	private String BillOriginal;
	private String BalanceOriginal;
	private String NumberItem;
	private String Comments;
	private String PrepareByCode;
	private String SupportCode;
	private String InChargeCode;
	private String LastAddEdit;
	private String CustFax;
	private String CustAddress1;
	private String AutoSoYN;
	private String CloseDate;
	private String CloseStatus;
	private String ConfirmDate;
	private String Gst;
	private String ValidityDays;
	private String ExpiryDt;
	private String IncoTerm;
	private String DeliveryComments;
	private String EntryStaff;
	private String EntryDate;
	private String LastAddEditStaff;
	private String LastAddEditDate;
	private String CSt;
	private String KSt;
	private String PSt;
	private String DSt;
	private String PONo;
	private String EventDate;
	private String EventTime;
	private String DeliveryDate;
	private String DeliveryTime;
	private String MenuID;
	private String MenuGroupID;
	private String NoPax;
	private String AgreedPrice;
	private String InlGST;
	private String CustDelAddBlock;
	private String CustDelAddNos;
	private String CustDelAddFloor;
	private String CustDelAddUnit;
	private String CustDelAddress1;
	private String CustDelAddBuilding;
	private String CustDelAddStreet;
	private String CustDelAddPostal;
	private String CustDelAddCountry;
	private String CustDelTelephone;
	private String CustDelFax;
	private String CustMobile;
	private String CustDelMobile;
	private String CustEmail;
	private String CustDelEmail;
	private String CustDelAtt;
	private String NoLift;
	private String NoParking;
	private String DelDate;
	private String DelTime;
	private String DelBy;
	private String VehicleNo;
	private String CollectionDate;
	private String CollectionTime;
	private String SchDelTime;
	private String SchDelDate;
	private String MealType;
	private String SchCollectionDate;
	private String SchCollectionTime;
	private String CollectionVehicleNo;
	private String ASt;
	private String LiftLanding;
	private String ColDate;
	private String ColTime;
	private String MainSoNo;
	private String DelYN;
	private String ColYN;
	private String GSTAmount;
	private String AppliedOriginal;
	private String GSTRate;
	private String VoidComments;
	private String InvNo;
	private String Rev;
	private String SchDeliveryStaff;

}
